apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rg0wugilg-go 
  janus-idp.io/tekton: rg0wugilg-go
  backstage.io/kubernetes-id: rg0wugilg-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rg0wugilg-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  