apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rg0wugilg-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rg0wugilg-go 
  name: rg0wugilg-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rg0wugilg-go 
